### ISSUE TITLE
Misnamed variable in callLineEdit.pyw

### ISSUE THREAD

**Issue by kimrojas** [PacktPublishing/Qt5-Python-GUI-Programming-Cookbook#4]
From the instruction in the book, the `labelResponse` variable is assigned to the "Enter your name" text. 
However, the current callLineEdit.pyw code and the one in the book states that this will be changed to "hello " +input.
This produces a different output in comparison to the expected output where the one that should be changed was the unedited label object. 

Solution: 
In callLineEdit.pyw (and in book), 
replace:     `self.ui.labelResponse.setText("Hello "+self.ui.lineEditName.text())`
to:   `self.ui.label.setText("Hello "+self.ui.lineEditName.text())`

**Comment by bmharwani** [comment]
Basically, the objectName property of the second Label widget has to be set to labelResponse instead of first Label widget. 
So, the correction is that the text in first step, "Set the objectName property of the Label widget to labelResponse"  has to be shifted to step 2. That's it
